strategies:
  # =================================================================
  # ORIGINAL STRATEGIES
  # =================================================================

  - id: supertrend_simple
    class: SupertrendStrategy
    enabled: true
    symbols:
      - ABB
      - ADANIENT
      - AMBER
      - BANKINDIA
      - BATAINDIA
    params:
      atr_period: 10              # Supertrend ATR period
      atr_multiplier: 3           # Supertrend multiplier
      min_hold_time_minutes: 5    # Minimum 5 minutes hold
      min_volume: 50              # Minimum volume filter
      position_size_pct: 0.1      # 10% of capital per trade
      max_position_size: 11000    # Max position size in rupees
    trailing_sl:
      type: atr
      atr_multiplier: 2.5         # Trailing stop (optional, Supertrend handles exits)
      atr_period: 10

  # =================================================================
  # NEW PROFESSIONAL INTRADAY STRATEGIES (INDIAN MARKET OPTIMIZED)
  # =================================================================

  # Strategy 1: VWAP + RSI Mean Reversion
  # Best for: Range-bound markets, sideways days
  # Win Rate: 60-70%
  - id: vwap_rsi_meanreversion
    class: VWAPRSIMeanReversionStrategy
    enabled: true
    symbols:
      - ABB
      - BATAINDIA
      - ADANIENT
    params:
      rsi_period: 14
      rsi_oversold: 30            # Buy when RSI < 30
      rsi_overbought: 70          # Sell when RSI > 70
      rsi_exit_long: 60           # Exit LONG when RSI > 60
      rsi_exit_short: 40          # Exit SHORT when RSI < 40
      vwap_deviation_pct: 1.0     # Entry when price deviates 1% from VWAP
      stop_loss_pct: 1.5          # 1.5% stop loss
      min_volume: 100
      position_size_pct: 0.05     # 5% of capital per trade
      max_position_size: 10000
      avoid_first_minutes: 15     # Avoid first 15 minutes
      avoid_last_minutes: 30      # Avoid last 30 minutes
    trailing_sl:
      type: fixed_pct
      pct: 1.5

  # Strategy 2: Opening Range Breakout (ORB)
  # Best for: Trending days, high volatility
  # Win Rate: 55-65%
  - id: opening_range_breakout
    class: OpeningRangeBreakoutStrategy
    enabled: true
    symbols:
      - ADANIENT
      - AMBER
      - BANKINDIA
    params:
      orb_period_minutes: 15      # First 15 minutes for range
      breakout_confirmation_pct: 0.1  # 0.1% above range high
      volume_multiplier: 1.5      # 1.5x average volume confirmation
      risk_reward_ratio: 2.0      # 1:2 risk/reward
      position_size_pct: 0.1      # 10% of capital
      max_position_size: 15000
    trailing_sl:
      type: atr
      atr_multiplier: 2.0
      atr_period: 14

  # Strategy 3: EMA Crossover + MACD Momentum
  # Best for: Trending markets, momentum plays
  # Win Rate: 50-60%
  - id: ema_macd_momentum
    class: EMAMACDMomentumStrategy
    enabled: true
    symbols:
      - ABB
      - BATAINDIA
      - AMBER
    params:
      fast_ema_period: 9          # Fast EMA
      slow_ema_period: 21         # Slow EMA
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      target_pct: 2.0             # 2% target
      stop_loss_pct: 1.0          # 1% stop loss
      trailing_sl_atr_mult: 1.5   # 1.5x ATR trailing SL
      atr_period: 14
      min_volume: 100
      min_ema_separation_pct: 0.2 # 0.2% minimum EMA separation
      position_size_pct: 0.08     # 8% of capital
      max_position_size: 12000
    trailing_sl:
      type: atr
      atr_multiplier: 1.5
      atr_period: 14

  # Strategy 4: Supertrend + ADX Trend Following
  # Best for: Strong trending markets, filtered signals
  # Win Rate: 65-70%
  - id: supertrend_adx_pro
    class: SupertrendADXStrategy
    enabled: true
    symbols:
      - ABB
      - ADANIENT
      - BANKINDIA
      - BATAINDIA
    params:
      atr_period: 10
      atr_multiplier: 3
      adx_period: 14
      adx_threshold: 25           # Strong trend > 25
      adx_exit_threshold: 20      # Exit when ADX < 20
      min_hold_time_minutes: 5
      use_atr_target: true        # Use ATR-based target
      atr_target_multiplier: 2.5  # 2.5x ATR target
      min_volume: 100
      position_size_pct: 0.1      # 10% of capital
      max_position_size: 15000
    trailing_sl:
      type: atr
      atr_multiplier: 2.5
      atr_period: 10
  
  - id: mtf_atr
    class: MultiTimeframeATRStrategy
    enabled: false
    symbols:
      - ADANIENT
      - BANKINDIA
      - ABB
      - BATAINDIA
      - AMBER
    params:
      fast_ema: 9
      slow_ema: 21
      trend_ema: 50
      atr_period: 14
      atr_multiplier: 2.0
      risk_reward_ratio: 3.0
      rsi_period: 14
      rsi_min: 30
      rsi_max: 70
      volume_period: 20
      min_volume_multiplier: 1.0
      position_size_pct: 0.02
    trailing_sl:
      type: atr
      atr_multiplier: 2.0
      atr_period: 14
  
  - id: scalping_pro
    class: ScalpingMTFATRStrategy
    enabled: false
    symbols:
      - ABB
      - BATAINDIA
      - ADANIENT
      - BANKINDIA
      - AMBER
    params:
      # EMA settings
      ema9: 9              # Fast EMA on 5-min
      ema21: 21            # Slow EMA on 5-min
      ema50_15m: 50        # Trend EMA on 15-min
      ema200_1h: 200       # Long-term trend on 1-hour
      
      # ATR settings
      atr_period: 14
      atr_sl_mult: 2.5     # Stop loss: 2.5 ATR
      atr_tp1_mult: 2.0    # TP1: 2 ATR
      atr_tp2_mult: 3.0    # TP2: 3 ATR
      atr_trail_mult: 2.0  # Trailing: 2 ATR
      
      # RSI settings
      rsi_period: 14
      rsi_long_min: 40     # LONG: 40-70
      rsi_long_max: 70
      rsi_short_min: 30    # SHORT: 30-60
      rsi_short_max: 60
      
      # Volume and entry
      volume_period: 20
      price_ema_dist: 0.2  # Price within 0.2 ATR of EMA9
      
      # Risk management
      risk_per_trade: 0.01      # 1% risk per trade
      max_positions: 2          # Max 2 concurrent positions
      daily_loss_limit: 0.025   # 2.5% daily loss limit
      max_consec_losses: 3      # Stop after 3 consecutive losses
      
      # Profit management
      breakeven_atr: 1.0        # Move to BE at 1 ATR profit
      trailing_start_atr: 1.5   # Start trailing at 1.5 ATR profit
      tp1_pct: 0.5              # Close 50% at TP1
      tp2_pct: 0.3              # Close 30% at TP2
    trailing_sl:
      type: atr
      atr_multiplier: 2.0
      atr_period: 14
